homeassistant:
  customize:
    package.node_anchors:
    # se orario inizio e fine vengono impostati entrambi in 00:00:00 le notifiche media_player saranno attive h24
      orario inizio notifica: &hours_start "09:00:00"
      orario fine notifica: &hours_end "22:00:00"

##############################################################
#         DA QUESTO PUNTO NON MODIFICARE
##############################################################
automation:
  - alias: notify_control_power_media_player
    id: notify_control_power_media_player
    mode: queued
    variables:
      volume: 0.4
      alexa: "{{ states.media_player | selectattr('attributes.source','eq','Local Speaker') | map(attribute='entity_id') | select('in', integration_entities('alexa_media')) | list }}"
      google: "{{ states.media_player | selectattr('attributes.device_class', 'defined') | selectattr('attributes.device_class', 'eq', 'speaker') | map(attribute='entity_id') | select('in', integration_entities('cast')) | list }}"
      volume_media_player: "{{ state_attr('sensor.volumi_media_player', 'list_device').values() | list }}"
    trigger:
      - platform: event
        event_type: customizations
        event_data:
          types: notify_power_control
    condition:
      - condition: time
        after: *hours_start
        before: *hours_end
    action:
      - alias: Imposta volume Notifica
        service: media_player.volume_set
        data:
          entity_id: "{{ google + alexa }}"
          volume_level: "{{ trigger.event.data.volume | default(volume) }}"
      - alias: INVIA NOTIFICA
        parallel:
          - alias: GOOGLE
            if: "{{ google | count > 0 }}"
            then:
              - service: tts.google_translate_say
                data:
                  entity_id: "{{ google }}"
                  message: "{{ trigger.event.data.message | default('Messaggio non impostato') }}"
          - alias: ALEXA
            if: >-
              {{ alexa | count > 0}}
            then:
              - service: notify.alexa_media
                data:
                  target: "{{ alexa }}"
                  data:
                    method: spoken
                  message: "{{ trigger.event.data.message | default('Messaggio non impostato') }}"
      - delay:
          seconds: "{{ (5 + (trigger.event.data.message | regex_replace('[a-zA-Z0-9]', '')).split()|count * 0.35 + trigger.event.data.message | count * 0.06) | round(0, default=5) }}"
      - repeat:
          for_each: "{{ alexa + google }}"
          sequence:
            - alias: Imposta volume Notifica
              service: media_player.volume_set
              data:
                entity_id: "{{ repeat.item }}"
                volume_level: "{{ volume_media_player[repeat.index - 1] }}"
